server:
  servlet:
    context-path: /system
  port: 8189
  error:
    include-stacktrace: never
    include-exception: false
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: aefiojfaofj3oq5j3p158m1fy181p1gj3158y13g1kp5hjgpw385g2
